runtime: python312 
entrypoint: gunicorn -b :$PORT naes2025.wsgi

handlers:
- url: /static
  static_dir: static_gcloud/
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5