# Generated by Django 5.2.1 on 2025-05-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_remove_product_stock_quantity_alter_stock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
